mysite/feed/urls.py
from unicodedata import name
from django.urls import path

from .views import HomePageView, PostDetailView, AddPostView 


app_name= 'feed'

urlpatterns = [
    path('',HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/',PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(),name='post' )
]

mysite/mysite/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from feed import urls as feed_url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(feed_url, namespace='feed'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/feed/models.py
from cgitb import text
from email.mime import image
from operator import truediv
from django.db import models
from sorl.thumbnail import ImageField

# Create your models here.

class Post(models.Model):
    text= models.CharField(max_length=140, blank=False,null=False)
    image= ImageField()

    def __str__(self) -> str:
        return self.text

mysite/feed/views.py
from django.views.generic import TemplateView, DetailView, FormView

from .form import PostForm

from .models import Post

class HomePageView(TemplateView):
    template_name='home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context ['posts'] = Post.objects.all()

        return context
    
class PostDetailView(DetailView):
    template_name = 'detail.html'
    model = Post 

class AddPostView(FormView):
    template_name = "new_post.html"
    form_class = PostForm
    succes_url = "/"

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <h1>
    {% block body %}
    {% endblock %}
   </h1>
</body>
</html>

mysite/templates/detail.html
{% extends 'base.html' %}

{% block body %}
    <a href="{% url 'feed:index' %}"> &larr; go back</a>
    <h3>text<h3/>
    {{object.text}}
    <h3>image<h3/>
    <img  src="{{ object.image.url }}"/>
    
{% endblock  %}

mysite/templates/home.html
{% extends "base.html" %}
{% load thumbnail%}

{% block body %}
    {% for post in posts %}
        <h1>{{ post.text }}</h1>
            <a href="{% url 'feed:detail' post.id %}" >
            {% thumbnail post.image "100x100" crop="center" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"/>
            {% endthumbnail %}
        </a>
    {% endfor %}
{% endblock %}

mysite/templates/new_post.html
{% extends "base.html" %}
{% load thumbnail%}

{% block body %}
  empty
{% endblock %}